#!/usr/bin/env bash
set -euo pipefail

repo="${FISHBONE_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
out="${SCIDATAHUB_AUDIT_DIR:-$repo/docs/internal/reference-audits/scidatahub}"
runner="$repo/scripts/reference-audit/opencode_scidatahub_audit.sh"
model="${SCIDATAHUB_AUDIT_MODEL:-${FWF_MODEL:-deepseek/deepseek-v4-pro}}"

usage() {
  cat <<'USAGE'
Usage:
  prepare_scidatahub_opencode_jobs.sh

Creates standalone opencode job scripts under:
  docs/internal/reference-audits/scidatahub/runs/

Run topic jobs in parallel if you want:
  bash docs/internal/reference-audits/scidatahub/runs/run-01-inventory.sh
  bash docs/internal/reference-audits/scidatahub/runs/run-02-domain.sh
  ...

After topic reports exist, run:
  bash docs/internal/reference-audits/scidatahub/runs/run-final-synthesis.sh

Environment:
  SCIDATAHUB_AUDIT_MODEL=deepseek/deepseek-v4-pro
  OPENCODE_EXTRA_ARGS=--auto
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

bash "$repo/scripts/reference-audit/collect_scidatahub_context.sh"
mkdir -p "$out/runs" "$out/logs" "$out/reports" "$out/prompts"

tasks=(inventory domain chain backend frontend benchmarks inherit)
idx=1
for task in "${tasks[@]}"; do
  script="$out/runs/run-$(printf '%02d' "$idx")-$task.sh"
  cat > "$script" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$repo"
export SCIDATAHUB_AUDIT_MODEL="\${SCIDATAHUB_AUDIT_MODEL:-$model}"
mkdir -p "$out/logs"
bash "$runner" --execute --skip-summary --task "$task" 2>&1 | tee "$out/logs/$task.log"
EOF
  chmod +x "$script"
  idx=$((idx + 1))
done

cat > "$out/runs/run-final-synthesis.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$repo"
export SCIDATAHUB_AUDIT_MODEL="\${SCIDATAHUB_AUDIT_MODEL:-$model}"
mkdir -p "$out/logs"
bash "$runner" --execute --task synthesis 2>&1 | tee "$out/logs/synthesis.log"
EOF
chmod +x "$out/runs/run-final-synthesis.sh"

cat > "$out/runs/run-all-sequential.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$repo"
for script in "$out"/runs/run-[0-9][0-9]-*.sh; do
  bash "\$script"
done
bash "$out/runs/run-final-synthesis.sh"
EOF
chmod +x "$out/runs/run-all-sequential.sh"

cat > "$out/RUNBOOK.md" <<EOF
# SciDataHub Opencode Jobs

Generated by \`scripts/reference-audit/prepare_scidatahub_opencode_jobs.sh\`.

## Parallel topic jobs

\`\`\`bash
bash $out/runs/run-01-inventory.sh
bash $out/runs/run-02-domain.sh
bash $out/runs/run-03-chain.sh
bash $out/runs/run-04-backend.sh
bash $out/runs/run-05-frontend.sh
bash $out/runs/run-06-benchmarks.sh
bash $out/runs/run-07-inherit.sh
\`\`\`

## Final synthesis

Run this after the topic reports are complete:

\`\`\`bash
bash $out/runs/run-final-synthesis.sh
\`\`\`

Reports are written to \`$out/reports/\`; raw logs are written to
\`$out/logs/\`.
EOF

echo "Prepared SciDataHub opencode job scripts in $out/runs"
echo "Read $out/RUNBOOK.md for the command list."
